CC = i386-mingw32-gcc
CFLAGS = 

DEPS = algo.h board.h
OBJ = main.o board.o algo.o

romov.exe: ${OBJ}
	${CC} -o $@ $^ ${CFLAGS}

.PHONY: clean

clean: 
	rm -f *.o

%.o: %.c ${DEPS}
	${CC} -c -o $@ $< ${CFLAGS}

